const express = require('express');
const route = express.Router();
const loginController = require('./src/controllers/loginController');
const {loginRequired, varGlobal} = require('./src/middlewares/middleware');
const homeController = require('./src/controllers/homeController');
const listController = require('./src/controllers/listController');
const estoqueController = require('./src/controllers/estoqueController');
const contatoController = require('./src/controllers/contatoController');

route.get('/', loginController.index);
route.post('/register', loginController.register);
route.post('/login', loginController.login);
route.get('/home', loginRequired, varGlobal, homeController.index);
route.get('/lists', loginRequired, varGlobal,homeController.index);
route.get('/home/createList',loginRequired, varGlobal,homeController.createList);
route.post('/home/createList/create',loginRequired, varGlobal,listController.create);
route.get(`/lists/:id`, loginRequired, varGlobal,listController.lists);
route.get(`/list/:name`, loginRequired, varGlobal,listController.openList);
route.post(`/edit/:name`, loginRequired, varGlobal,listController.edit);
route.get(`/delete/:name`, loginRequired, varGlobal,listController.delete);
route.get('/logout', loginRequired, loginController.logout);
route.get('/estoque', loginRequired, varGlobal, estoqueController.index);
route.post('/estoque/save', loginRequired, varGlobal, estoqueController.create);
route.get('/deleteEstoque/:id', loginRequired, varGlobal, estoqueController.delete);
route.get('/estoque/push/:id', loginRequired, varGlobal, estoqueController.loadEdit);
route.post('/estoque/edit/:id', loginRequired, varGlobal, estoqueController.saveEdit);
route.get('/estoque/total', loginRequired, varGlobal, estoqueController.total);
route.get('/contato', loginRequired, varGlobal, contatoController.index);
module.exports = route;